=== rbygrave/sourceforge-ebean/ebean/branches/trunk_paul/src/site/resources/xsd/DatabasePlatformSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.avaje.org/DatabasePlatformSchema"
	xmlns:ebean="http://www.avaje.org/DatabasePlatformSchema"
	elementFormDefault="qualified">

	<element name="dbmsCatalog">
		<complexType>
			<sequence>
				<element maxOccurs="unbounded" minOccurs="0" ref="ebean:dbmsProduct" />
			</sequence>
			<attribute ref="ebean:adaptorClass" />
		</complexType>
	</element>


	<attribute name="adaptorClass" type="string"></attribute>
	<element name="dbmsVersion">
		<complexType>
			<sequence>
				<element minOccurs="0" name="eBeanName" type="string" maxOccurs="unbounded"></element>
				<element minOccurs="0" maxOccurs="unbounded"
					name="dbName" type="string" />
			</sequence>
			<attribute ref="ebean:adaptorClass" />
			<attribute name="minVersion" type="int"></attribute>
			<attribute name="maxVersion" type="int"></attribute>
		</complexType>
	</element>
	<element name="dbmsProduct">
		<complexType>
			<sequence>
				<element minOccurs="0" maxOccurs="unbounded" name="dbNamePrefix"
					type="string" />
				<element minOccurs="0" maxOccurs="unbounded" name="eBeanName"
					type="string" />
				<element minOccurs="0" maxOccurs="unbounded" ref="ebean:dbmsVersion" />
			</sequence>
			<attribute ref="ebean:adaptorClass" />
		</complexType>
	</element>
</schema>

=== rbygrave/sourceforge-ebean/ebean/trunk/src/main/resources/com/avaje/ebean/config/dbplatform/dbms.xml
<?xml version="1.0" encoding="UTF-8"?>
<dbmsCatalog
	xmlns="file://E:/workspace/ebean-svn/src/site/resources/DatabasePlatformSchema.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.avaje.org/DatabasePlatformSchema DatabasePlatformSchema.xsd "
	adaptorClass="com.avaje.ebean.config.dbplatform.GenericDatabasePlatform">
	<dbmsProduct adaptorClass="com.avaje.ebean.config.dbplatform.Oracle10Platform">
		<dbNamePrefix>oracle</dbNamePrefix>
		<eBeanName>oracle</eBeanName>
		<eBeanName>oracle10</eBeanName>
		<eBeanName>oracle9</eBeanName>
	</dbmsProduct>
	<dbmsProduct adaptorClass="com.avaje.ebean.config.dbplatform.MsSqlServer2005Platform">
		<dbNamePrefix>microsoft</dbNamePrefix>
		<eBeanName>sqlserver2005</eBeanName>
		<dbmsVersion maxVersion="8" adaptorClass="com.avaje.ebean.config.dbplatform.MsSqlServer2000Platform">
			<eBeanName>sqlserver2000</eBeanName>
		</dbmsVersion>
	</dbmsProduct>
	<dbmsProduct adaptorClass="com.avaje.ebean.config.dbplatform.MySqlPlatform">
		<dbNamePrefix>mysql</dbNamePrefix>
		<eBeanName>mysql</eBeanName>
	</dbmsProduct>
	<dbmsProduct adaptorClass="com.avaje.ebean.config.dbplatform.PostgresPlatform">
		<dbNamePrefix>postgres</dbNamePrefix>
		<eBeanName>postgres83</eBeanName>
	</dbmsProduct>
	<dbmsProduct adaptorClass="com.avaje.ebean.config.dbplatform.H2Platform">
		<dbNamePrefix>h2</dbNamePrefix>
		<eBeanName>h2</eBeanName>
	</dbmsProduct>
	<dbmsProduct adaptorClass="com.avaje.ebean.config.dbplatform.DB2Platform">
		<dbNamePrefix>db2</dbNamePrefix>
		<dbNamePrefix>ids</dbNamePrefix>
		<dbmsVersion adaptorClass="com.avaje.ebean.config.dbplatform.DB2Platform">
			<dbName>DB2Â®</dbName>
			<dbName>DB2/LINUXX8664</dbName>
			<dbName>IDS/UNIX64</dbName>
		</dbmsVersion>
	</dbmsProduct>
</dbmsCatalog>
